# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7e585dccf07fdb7372d8fbd8e4552c5912c323848aadde38f1216d7b8a166b439d0cb8071ada55c7800c2194a47b268d78b9f255f70c6bf44aae61ef176c06e

test:
  secret_key_base: dffcc31c9c9fc55434a84b141298d58162718bf47c3ce7bcd3efd90dfe5251917c405d37f3405a0aa78d829440477e33b04c40c20a0f0157b25f1d2ad6e27862

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
